pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=2"
    actions:
      merge:
        method: merge
      label:
        add: ["hacktoberfest-accepted"] 
  - name: automatic merge for ImgBot pull requests
    conditions:
      - author=imgbot[bot]
      - status-success=Travis CI - Pull Request
    actions:
      merge:
        method: merge